### ISSUE TITLE
When running 'stable_maselines3_ example. py', some module names were found to have issues.

### ISSUE THREAD

**Issue by YanShangSHan** [edbeeching/godot_rl_agents#215]
1. **stable_maselines3_ example. py**   line 11
“export_model_as_onnx” -> "export_ppo_model_as_onnx"
2. **stable_baselines_export.py**   line 2
"spaces" -> "space_utils"

I don't know if this modification is correct, but the program can run normally after the modification.

**Comment by Ivan-267** [comment]
Hello and thank you for posting these.

Could you try to reinstall gdrl using `pip install https://github.com/edbeeching/godot_rl_agents/archive/refs/heads/main.zip` to get the latest version (previous version may need to be uninstalled first). With the newest version, no modifications should be needed.

1. The method name has changed in one of our updates, which is still not reflected in the latest release.
2. This is likely because of the newest SB3 using newer gymnasium. For now we limited the SB3 version until we can test the changes to support the newer version (the changes from point 2 may be sufficient, we just didn't check it yet).

**Comment by YanShangSHan** [comment]
thanks,i will have a try
