### ISSUE TITLE
cannot import name 'spaces' from 'gymnasium.vector.utils'

### ISSUE THREAD

**Issue by izavala97** [edbeeching/godot_rl_agents#216]
Recently i got this issue
```
Traceback (most recent call last):
  File "/Users/izavala/Documents/godot-omniverse/stable_baselines3_example.py", line 11, in <module>
    from godot_rl.wrappers.onnx.stable_baselines_export import export_model_as_onnx
  File "/Users/izavala/.local/lib/python3.12/site-packages/godot_rl/wrappers/onnx/stable_baselines_export.py", line 2, in <module>
    from gymnasium.vector.utils import spaces
ImportError: cannot import name 'spaces' from 'gymnasium.vector.utils' (/Users/izavala/.local/lib/python3.12/site-packages/gymnasium/vector/utils/__init__.py)
```
I saw from Gymnasium lib utils 
https://github.com/Farama-Foundation/Gymnasium/tree/main/gymnasium/vector/utils
that `spaces.py` file has been moved to
https://github.com/Farama-Foundation/Gymnasium/blob/main/gymnasium/spaces/space.py

**Comment by izavala97** [comment]
similar error
```
Traceback (most recent call last):
  File "/Users/izavala/Documents/godot-omniverse/stable_baselines3_example.py", line 11, in <module>
    from godot_rl.wrappers.onnx.stable_baselines_export import export_model_as_onnx
ImportError: cannot import name 'export_model_as_onnx' from 'godot_rl.wrappers.onnx.stable_baselines_export' (/Users/izavala/.local/lib/python3.12/site-packages/godot_rl/wrappers/onnx/stable_baselines_export.py). Did you mean: 'export_ppo_model_as_onnx'?
```

**Comment by izavala97** [comment]
i can fix this, please give me permission to create a new branch and open a new PR

**Comment by Ivan-267** [comment]
> i can fix this, please give me permission to create a new branch and open a new PR

Hello, thanks for reporting the error, we are already aware of the issue (https://github.com/edbeeching/godot_rl_agents/issues/215).
Both errors should be fixed in the new version `pip install https://github.com/edbeeching/godot_rl_agents/archive/refs/heads/main.zip`.

Please verify that this works first. You may need to uninstall the currently installed version before that.

For now it just installs a previous version of SB3 which is already well tested with GDRL. We plan to update the gym version in a future update too.

You can feel free to submit the fix for the gymnasium version by making a fork of the repository and submitting the fix as PR (Ed, the repository owner, can make you a collaborator on request, but until then you can just PR from the fork if you wish). The `'export_model_as_onnx'` export issue shouldn't need any fixing when using the latest version of GDRL from the main branch.

Again, thanks for testing out GDRL and offering to contribute.

**Comment by izavala97** [comment]
great!, i will close this issue since is a duplicated
