### ISSUE TITLE
Training stuck in "PENDING" status and editor not connecting

### ISSUE THREAD

**Issue by TeDeJamaica** [edbeeching/godot_rl_agents#3]
I followed the installation instructions provided, everything goes well, but couldn't train nor use the pretrained models from any of the example envs.
First of all when I use the following command:

> gdrl --env_path envs/builds/JumperHard/jumper_hard.x86_64 --config_path envs/configs/ppo_config_jumper_hard.yaml

It says

> usage: gdrl [-h] [--env_path ENV_PATH] [-f CONFIG_FILE] [-c RESTORE] [-e]
> gdrl: error: unrecognized arguments: --config_path envs/configs/ppo_config_jumper_hard.yaml

So I just changed the argument `--config_path` to `-f` and now it works, but...

> == Status ==
> Memory usage on this node: 6.1/15.5 GiB
> Using FIFO scheduling algorithm.
> Resources requested: 0/4 CPUs, 0/0 GPUs, 0.0/7.38 GiB heap, 0.0/3.69 GiB objects
> Result logdir: /home/hibiscus-tea/ray_results/PPO/jumper_hard
> Number of trials: 1/1 (1 PENDING)
> +-----------------------+----------+-------+
> | Trial name            | status   | loc   |
> |-----------------------+----------+-------|
> | PPO_godot_0479d_00000 | PENDING  |       |
> +-----------------------+----------+-------+

It stays like that forever. Neither running jumper_hard.x86_64 or running the game from the editor changes anything.
If I use the pretrained model command it stays the same.
I tried the same process on Windows 10 and I get the same results. I think I am missing something. 
The editor outputs this:

> getting command line arguments
> Waiting for one second to allow server to start
> trying to connect to server
> 03

If I change the const DEFAULT_PORT to 6007 (the default godot port) it outputs this:

> getting command line arguments
> Waiting for one second to allow server to start
> trying to connect to server
> 02
> performing handshake
> server disconnected, closing

I hope you help me with this issue. This project looks amazing and I am looking forward to the multi-agents update. :)

**Comment by edbeeching** [comment]
Thank you for your issue. It highlights some parts of the docs that are not clear.

I have tested the Library on windows 7, so it should work on Windows 10.
There are a number of problems.

### Interactive training
Before trying the points below, can you try launching interactive training by typing "gdrl" in the terminal and then pressing play in the godot editor, this should work. If it does not please let me know what is output in the terminals of Windows (powershell?) and the Godot editor.

### Training on Windows
For training on windows, you will need to use the windows exports of the environments. That end in .exe
So the command will be:
```
gdrl --env_path envs/builds/JumperHard/jumper_hard.exe -f envs/configs/ppo_config_jumper_hard.yaml
```
(thank you for identifying the issue with --config_path, I will look into it)


### The reason for PENDING
Rays job launching system "Ray Tune", does a check that there are enough cpus on your machine in order to launch the training. Which in this case requires 5 cpu cores. Your machine appears to have 4 cores, so the job gets stuck in pending. A quick fix is to lower the number of workers in the config file to 3.
```
num_workers: 3
``` 
I am start to think using Ray Tune in this setting is a bit overkill and I could revert to a much simpler method of training.



Let me know how it goes.

**Comment by TeDeJamaica** [comment]
Thank you! It's working now. I also had to change `num_gpus` to 0 since I'm using an integrated graphics card. It's working both on Windows 10 & Linux.

One last problem I found out is that the game doesn't run when using

> gdrl --env_path envs/builds/JumperHard/jumper_hard.exe -f envs/configs/ppo_config_jumper_hard.yaml

It seems that the training is running as expected, but the game is not showing up anywhere, even though godot outputs are poping up in the terminal. Instead if I use `gdrl` or the pretrained models command, the game shows up and everything seems to work out.

**Comment by edbeeching** [comment]
Good news. When you run the training it runs in windowless mode by default. If you want to see the game running which training change the following option in the config to true. 
```
show_window: true
```

I will close the issue but feel free to reopen it if you have any other problems
